### ISSUE TITLE
i cannot install this add-ons

### ISSUE THREAD

**Issue by robbiibadi** [znry27/odoo_sh#1]
when i try to install this add-ons , i get this error

> Error:
> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/odoo/odoo-server/odoo/tools/convert.py", line 757, in parse
>     self._tags[rec.tag](rec, de, mode=mode)
>   File "/odoo/odoo-server/odoo/tools/convert.py", line 612, in _tag_record
>     raise Exception("Cannot update missing record %r" % xid)
> Exception: Cannot update missing record 'payment.payment_acquirer_midtrans'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/odoo/odoo-server/odoo/http.py", line 653, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/odoo/odoo-server/odoo/http.py", line 312, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/odoo/odoo-server/odoo/http.py", line 695, in dispatch
>     result = self._call_function(**self.params)
>   File "/odoo/odoo-server/odoo/http.py", line 344, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/odoo/odoo-server/odoo/http.py", line 337, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/odoo/odoo-server/odoo/http.py", line 938, in __call__
>     return self.method(*args, **kw)
>   File "/odoo/odoo-server/odoo/http.py", line 517, in response_wrap
>     response = f(*args, **kw)
>   File "/odoo/odoo-server/addons/web/controllers/main.py", line 966, in call_button
>     action = self._call_kw(model, method, args, {})
>   File "/odoo/odoo-server/addons/web/controllers/main.py", line 954, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/odoo/odoo-server/odoo/api.py", line 749, in call_kw
>     return _call_kw_multi(method, model, args, kwargs)
>   File "/odoo/odoo-server/odoo/api.py", line 736, in _call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "<decorator-gen-61>", line 2, in button_immediate_install
>   File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 71, in check_and_log
>     return method(self, *args, **kwargs)
>   File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 442, in button_immediate_install
>     return self._button_immediate_function(type(self).button_install)
>   File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 535, in _button_immediate_function
>     modules.registry.Registry.new(self._cr.dbname, update_module=True)
>   File "/odoo/odoo-server/odoo/modules/registry.py", line 86, in new
>     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
>   File "/odoo/odoo-server/odoo/modules/loading.py", line 426, in load_modules
>     loaded_modules, update_module, models_to_check)
>   File "/odoo/odoo-server/odoo/modules/loading.py", line 318, in load_marked_modules
>     perform_checks=perform_checks, models_to_check=models_to_check
>   File "/odoo/odoo-server/odoo/modules/loading.py", line 224, in load_module_graph
>     load_data(cr, idref, mode, kind='data', package=package, report=report)
>   File "/odoo/odoo-server/odoo/modules/loading.py", line 68, in load_data
>     tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
>   File "/odoo/odoo-server/odoo/tools/convert.py", line 801, in convert_file
>     convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
>   File "/odoo/odoo-server/odoo/tools/convert.py", line 864, in convert_xml_import
>     obj.parse(doc.getroot(), mode=mode)
>   File "/odoo/odoo-server/odoo/tools/convert.py", line 754, in parse
>     self.parse(rec, mode)
>   File "/odoo/odoo-server/odoo/tools/convert.py", line 763, in parse
>     exc_info[2]
>   File "/odoo/odoo-server/odoo/tools/pycompat.py", line 86, in reraise
>     raise value.with_traceback(tb)
>   File "/odoo/odoo-server/odoo/tools/convert.py", line 757, in parse
>     self._tags[rec.tag](rec, de, mode=mode)
>   File "/odoo/odoo-server/odoo/tools/convert.py", line 612, in _tag_record
>     raise Exception("Cannot update missing record %r" % xid)
> odoo.tools.convert.ParseError: "Cannot update missing record 'payment.payment_acquirer_midtrans'" while parsing /odoo/custom/addons/payment_midtrans/data/payment_acquirer_data.xml:4, near
> <record id="payment.payment_acquirer_midtrans" model="payment.acquirer">
>       <field name="name">Midtrans</field>
>       <field name="image" type="base64" file="payment_midtrans/static/src/img/midtrans_icon.png"/>
>       <field name="provider">midtrans</field>
>       <field name="company_id" ref="base.main_company"/>
>       <field name="view_template_id" ref="midtrans_acquirer_button"/>
>       <field name="environment">test</field>
>       <field name="pre_msg">
> &lt;p&gt;You will be redirected to the Midtrans website after clicking on the payment button.&lt;/p&gt;</field>
>       <field name="midtrans_method">snap</field>
>       <field name="midtrans_merchant_id">dummy</field>
>       <field name="midtrans_client_key">dummy</field>
>       <field name="midtrans_server_key">dummy</field>
>     </record>

**Comment by znry27** [comment]
What version of Odoo you used ? This module tested on Odoo version 11.

For Odoo version 12, i will tested soon

**Comment by znry27** [comment]
Bug fixed for Odoo 12

Please check here https://github.com/znry27/payment_midtrans/tree/odoo-12

**Comment by robbiibadi** [comment]
now another issues comes up:

> Error:
> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/odoo/odoo-server/odoo/http.py", line 653, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/odoo/odoo-server/odoo/http.py", line 312, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/odoo/odoo-server/odoo/http.py", line 695, in dispatch
>     result = self._call_function(**self.params)
>   File "/odoo/odoo-server/odoo/http.py", line 344, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/odoo/odoo-server/odoo/http.py", line 337, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/odoo/odoo-server/odoo/http.py", line 938, in __call__
>     return self.method(*args, **kw)
>   File "/odoo/odoo-server/odoo/http.py", line 517, in response_wrap
>     response = f(*args, **kw)
>   File "/odoo/odoo-server/addons/web/controllers/main.py", line 966, in call_button
>     action = self._call_kw(model, method, args, {})
>   File "/odoo/odoo-server/addons/web/controllers/main.py", line 954, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/odoo/odoo-server/odoo/api.py", line 749, in call_kw
>     return _call_kw_multi(method, model, args, kwargs)
>   File "/odoo/odoo-server/odoo/api.py", line 736, in _call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "<decorator-gen-61>", line 2, in button_immediate_install
>   File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 71, in check_and_log
>     return method(self, *args, **kwargs)
>   File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 442, in button_immediate_install
>     return self._button_immediate_function(type(self).button_install)
>   File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 535, in _button_immediate_function
>     modules.registry.Registry.new(self._cr.dbname, update_module=True)
>   File "/odoo/odoo-server/odoo/modules/registry.py", line 86, in new
>     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
>   File "/odoo/odoo-server/odoo/modules/loading.py", line 426, in load_modules
>     loaded_modules, update_module, models_to_check)
>   File "/odoo/odoo-server/odoo/modules/loading.py", line 318, in load_marked_modules
>     perform_checks=perform_checks, models_to_check=models_to_check
>   File "/odoo/odoo-server/odoo/modules/loading.py", line 181, in load_module_graph
>     load_openerp_module(package.name)
>   File "/odoo/odoo-server/odoo/modules/module.py", line 368, in load_openerp_module
>     __import__('odoo.addons.' + module_name)
>   File "/odoo/odoo-server/odoo/modules/module.py", line 82, in load_module
>     exec(open(modfile, 'rb').read(), new_mod.__dict__)
>   File "<string>", line 1, in <module>
>   File "/odoo/odoo-server/addons/payment_midtrans/controllers/__init__.py", line 3, in <module>
>     import main
> ImportError: No module named 'main'

thanks for your response

**Comment by znry27** [comment]
Are you sure use odoo-12 or odoo-11 branch ? 

That error indicate that you use master branch in Odoo 11 or Odoo 12. If your Odoo version is 12 please use odoo-12 branch of this repository => https://github.com/znry27/payment_midtrans

And if you have another issue please open on that.
